# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dogfood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dogfood

  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
end
